# SOURCE: https://github.com/backstage/backstage/issues/4123
site_name: 'mock-docs'
site_description: 'mock-docs site description'

nav:
  - Home: index.md
  - SubDocs: '!include ./sub-docs/mkdocs.yml'
  - Plugins: '*include ./plugins/*/mkdocs.yml'

theme:
  name: material
  highlightjs: true

plugins:
  - techdocs-core

markdown_extensions:
  - markdown_inline_mermaid
